CREATE TABLE IF NOT EXISTS member (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID  NULL,
    login_name VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    currency VARCHAR(50) NOT NULL,
    full_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE,
    avatar VARCHAR(255),
    phone VARCHAR(255) NOT NULL,
    email_verify_status SMALLINT NOT NULL DEFAULT 1,
    phone_verify_status SMALLINT NOT NULL DEFAULT 1,
    date_of_birth TIMESTAMP,
    language VARCHAR(100),
    country VARCHAR(100),
    salt VARCHAR(100),
    rands VARCHAR(100),
    affiliate_id BIGINT,
    address VARCHAR(255),
    city VARCHAR(255),
    postal_code INTEGER,
    account_type INTEGER NOT NULL DEFAULT 1,
    last_login_date TIMESTAMP,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
