// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/apis/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMemberAccountCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	LoginName     string                 `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	FullName      string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberAccountCommand) Reset() {
	*x = CreateMemberAccountCommand{}
	mi := &file_pkg_apis_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberAccountCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberAccountCommand) ProtoMessage() {}

func (x *CreateMemberAccountCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberAccountCommand.ProtoReflect.Descriptor instead.
func (*CreateMemberAccountCommand) Descriptor() ([]byte, []int) {
	return file_pkg_apis_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMemberAccountCommand) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *CreateMemberAccountCommand) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *CreateMemberAccountCommand) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateMemberAccountCommand) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMemberAccountCommand) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type CreateMemberAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberAccountResponse) Reset() {
	*x = CreateMemberAccountResponse{}
	mi := &file_pkg_apis_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberAccountResponse) ProtoMessage() {}

func (x *CreateMemberAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateMemberAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_payment_payment_proto_rawDescGZIP(), []int{1}
}

var File_pkg_apis_payment_payment_proto protoreflect.FileDescriptor

const file_pkg_apis_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/apis/payment/payment.proto\x12\x02v1\"\xa9\x01\n" +
	"\x1aCreateMemberAccountCommand\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\x12\x1d\n" +
	"\n" +
	"login_name\x18\x02 \x01(\tR\tloginName\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\"\x1d\n" +
	"\x1bCreateMemberAccountResponse2c\n" +
	"\aPayment\x12X\n" +
	"\x13CreateMemberAccount\x12\x1e.v1.CreateMemberAccountCommand\x1a\x1f.v1.CreateMemberAccountResponse\"\x00B&Z$money-transfer-demo/pkg/apis/paymentb\x06proto3"

var (
	file_pkg_apis_payment_payment_proto_rawDescOnce sync.Once
	file_pkg_apis_payment_payment_proto_rawDescData []byte
)

func file_pkg_apis_payment_payment_proto_rawDescGZIP() []byte {
	file_pkg_apis_payment_payment_proto_rawDescOnce.Do(func() {
		file_pkg_apis_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_payment_payment_proto_rawDesc), len(file_pkg_apis_payment_payment_proto_rawDesc)))
	})
	return file_pkg_apis_payment_payment_proto_rawDescData
}

var file_pkg_apis_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_apis_payment_payment_proto_goTypes = []any{
	(*CreateMemberAccountCommand)(nil),  // 0: v1.CreateMemberAccountCommand
	(*CreateMemberAccountResponse)(nil), // 1: v1.CreateMemberAccountResponse
}
var file_pkg_apis_payment_payment_proto_depIdxs = []int32{
	0, // 0: v1.Payment.CreateMemberAccount:input_type -> v1.CreateMemberAccountCommand
	1, // 1: v1.Payment.CreateMemberAccount:output_type -> v1.CreateMemberAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_apis_payment_payment_proto_init() }
func file_pkg_apis_payment_payment_proto_init() {
	if File_pkg_apis_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_payment_payment_proto_rawDesc), len(file_pkg_apis_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_payment_payment_proto_goTypes,
		DependencyIndexes: file_pkg_apis_payment_payment_proto_depIdxs,
		MessageInfos:      file_pkg_apis_payment_payment_proto_msgTypes,
	}.Build()
	File_pkg_apis_payment_payment_proto = out.File
	file_pkg_apis_payment_payment_proto_goTypes = nil
	file_pkg_apis_payment_payment_proto_depIdxs = nil
}
